### ISSUE TITLE
App doesn't work when third-party cookies are disabled. 

### ISSUE THREAD

**Issue by mpallone** [udacity/ud989-retain#5]
When I cloned this app and opened it in my browser, nothing happened. The console threw this error: 

https://www.chromium.org/for-testers/bug-reporting-guidelines/uncaught-securityerror-failed-to-read-the-localstorage-property-from-window-access-is-denied-for-this-document

**Comment by vitaliyterziev** [comment]
I guess this is to be expected, you do need the localStorage in order to run the example, just do not block it

**Comment by mpallone** [comment]
I think Udacity should consider mentioning this in the lesson. 

Althoug, one could argue that googling around and solving this issue is something a web programmer should be able to do.

**Comment by anthonyattard** [comment]
Thanks for this.
